# This is the common Makefile which be included for all sub Makefiles
# All the global settings should set at here

AR = ar -rcs

COMMON_FLAGS += -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wfloat-equal -Wpadded -Winline -Wdisabled-optimization -g -Werror -Wstack-protector -pipe
