# This is the common Makefile which be included for all sub Makefiles
# All the global settings should set at here

AR = ar -rcs

COMMON_FLAGS += -Wall -Wextra -Wno-unused-parameter -Wno-unused-function
COMMON_FLAGS += -Wfloat-equal -Wpadded -Winline -Wdisabled-optimization
COMMON_FLAGS += -Wformat -Wformat-security -Werror=format-security
COMMON_FLAGS += -g -ggdb3 -pipe -fstack-protector
